theme: jekyll-theme-minimal
title: Arnau Lafuente's homepage
description: The "CV and Portfolio Showcase" repository is a comprehensive collection of my professional curriculum vitae (CV) and a visually appealing portfolio.
